#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

LOG_INFORMATION="\e[35mInformation:\e[0m "
UNMATCHABLE_FILTER="FullyQualifiedName=0"

# Detect JUNIT
JUNIT_DETECTED=$(dotnet test -c Release --filter $UNMATCHABLE_FILTER -l "junit" > /dev/null 2>&1; echo $?)
echo "$JUNIT_DETECTED"

if [[ "$JUNIT_DETECTED" -eq 0 ]]
    then echo -e "$LOG_INFORMATION Using junit logger"; export WITH_JUNIT='-l:"junit"'
    else echo -e "$LOG_INFORMATION Not using junit logger"; export WITH_JUNIT=''
fi

echo "$WITH_JUNIT"
dotnet test -c Release -l "console;verbosity=detailed" "$WITH_JUNIT"
